version: 2.1
orbs:
  sauce-connect: saucelabs/sauce-connect@volatile
workflows:
  basic_workflow:
    jobs:
      - saucelabs/with_proxy:
          steps:
            - run: npm start
            - run: node browserstack.runner.js -c nightwatch-browserstack.conf.js -e safari,chrome,chromeMac,firefox,iphone,pixel,galaxys9,ucbrowser

